### ISSUE TITLE
All articles are being served as type 9

### ISSUE THREAD

**Issue by jamestomasino** [muffinista/gopherpedia.com#1]
Recently all of the gopherpedia articles have been served up as binary types rather than type 0. I'm assuming it's a typo that led to the issue, but can't be sure. Manually linking to the content with type 0 works fine, but your gophermaps are serving up the links incorrectly. This can be seen on the root page as well as on search results.

**Comment by muffinista** [comment]
Thanks very much for the heads up. This is fixed in production now, and the commit will show up here once I clean up a couple other things.
