### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by shabbyrobe** [muffinista/gopherpedia.com#6]
I realise it's a contentious topic and I apologise in advance if I step out of line, but I feel I should raise the lack of a project license here in the tracker.

I noticed that gopher2000 uses the WTFPL, but there is a lot of concern about the vagueness of the WTFPL, the lack of a warranty disclaimer, concerns over public domain in certain jurisdictions (Germany), lack of FSF + OSI approval, aversion within the legal departments of various [800 pound gorillas](https://opensource.google/docs/thirdparty/licenses/#wtfpl-not-allowed).

It may be too late to relicense gopher2000 (even if there is willingness to consider it) if the number of contributors is high, but I would like to suggest licensing gopherpedia under an "OSI/FSF approved and recommended" permissive license instead.

I am absolutely, without a shadow of a doubt, _not_ a lawyer and this is not legal advice of any kind, but the two that seem to me to be the most spiritually aligned with the WTFPL are [CC0](http://creativecommons.org/publicdomain/zero/1.0/) and [Unlicense](https://unlicense.org/). Unfortunately, neither have the backing of both the FSF and the OSI. In the former case, the FSF explicitly recommends [CC0 over Unlicense](https://www.gnu.org/licenses/license-list.en.html#Unlicense), but the OSI were [unable to reach a consensus](https://opensource.org/faq#cc-zero) on CC0. This is making my head spin!

Having said all that, I'd probably just suggest taking the "safe route" and going with a BSD/MIT-alike or GPLv3.

**Comment by muffinista** [comment]
I agree that WTFPL isn't ideal. I'm going to take a little time to think about this one though.

**Comment by shabbyrobe** [comment]
> I'm going to take a little time to think about this one though.

Of course! It would be remiss to do otherwise :smile: Thanks for considering it.

**Comment by shabbyrobe** [comment]
Hello muffinista, I was wondering if you had had any thoughts about the licensing of gopherpedia/gopher2000 since last we spoke?

**Comment by muffinista** [comment]
Hi! Funny you should ask. I [added GPLv3 as a license](https://github.com/muffinista/gopherpedia.com/commit/945cab16f3ca042b57167f96b0a3f84ce39df761) both here and to gopher2000 a week or so ago and forgot to reference this issue.

**Comment by shabbyrobe** [comment]
Hahaha that's amazing, quite serendipitous timing. Thanks for updating. I probably should've checked the repo before I bumped 😆
